apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: www.areya-demo.xyz
      http:
        paths:
          - path: /api/v1/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /api/v1/hospitals-srv/?(.*)
            backend:
              serviceName: hospitals-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
