name: Deploy Manifests

on:
  push:
    branches: [ main ]
    paths: 
      - 'infra/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}  
    - name: Configure Kubernetes Clusters
      run: doctl kubernetes cluster kubeconfig save areya-k8s-cluster
    - name: Apply K8s infra
      run: kubectl apply -f infra/k8s 
